# Generated by Django 5.2.7 on 2025-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('faculty_id', models.CharField(max_length=50, unique=True)),
                ('valid_through', models.DateField()),
                ('photo', models.ImageField(upload_to='faculty_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('enrolment_no', models.CharField(max_length=50, unique=True)),
                ('valid_through', models.DateField()),
                ('photo', models.ImageField(upload_to='students_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('photo', models.ImageField(upload_to='visitor_photos/')),
            ],
        ),
    ]
