# Generated by Django 5.2.7 on 2025-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='valid_through',
            field=models.DateField(blank=True, default='2029-07-31', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_through',
            field=models.DateField(blank=True, default='2029-07-31', null=True),
        ),
    ]
